[package]
name = "summit_surveyor_bin"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
summit_surveyor = {path="../summit_surveyor"}
sukakpak = {path="../sukakpak"}
