[package]
name = "ass_bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ass_lib = {path="../ass_lib"}
structopt="0.3"
