[package]
name = "sukakpak"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generational-arena = "0.2.8"
ash = "0.32.1"
backtrace = "0.3"
winit = "0.24.0"
nalgebra = "0.27.1"
anyhow = "1.0.40"
ash-window = "0.6.0"
gpu-allocator = "0.7.0"
phf = {version="0.8.0",features=["macros"]}
image = "0.23.14"