[package]
name = "sukakpak"
version = "0.2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generational-arena = "0.2.8"
ash = "0.32.1"
backtrace = "0.3"
winit = "0.25.0"
tobj = "3.0.1"
nalgebra = "0.29.0"
anyhow = "1.0.40"
ash-window = "0.6.0"
gpu-allocator = "0.8.0"
phf = {version="0.8.0",features=["macros"]}
image = "0.23.14"
thiserror = "1.0.25"
cfg-if="1.0"
ass_lib = {path = "../ass_lib"}
free_list = {path = "../free_list"}
[features]
default = ["full_debug"]
full_debug = ["state_validation"]
no_validation=[]
state_validation = []
